config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get "others/users"
  resources :others
  devise_for :users

   root 'purchases#index'

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  def self.user_purchases(id)
    self.where("user_id = ?", id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :purchases
  attr_accessor :login
  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
  before_action :authenticate_user!
  before_filter :is_admin?
  # GET /purchases
  # GET /purchases.json
  def is_admin?
    if current_user.admin?
      true
    else
      false
    end
  end

  def index

  end

  def users

  end

  def show

  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /purchases
  # GET /purchases.json
  def index
    if current_user.admin?
      @purchases = Purchase.all
    else
      @purchases = Purchase.user_purchases(current_user.id)
    end
  end
  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user_id = current_user.id
    @purchase.status = 0
    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:file_url, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prototype</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if flash[:error] %>
    <div id="error">
      <%= flash[:error] %>
    </div>
<% end %>
<div id="banner">
  <%= image_tag("logo.png") %>
  <%= @page_title || "Photocopy Shop WebSite" %>
</div>

<div id="columns">

  <div id="side">
    <p><% if user_signed_in? %>
        Welcome <%= current_user.email %>! Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or
        <%= link_to "Sign in", new_user_session_path %>.
    <% end %></p>
    <ul>
    <li><a href="http://www....">Home</a></li>
    <li><a href="http://www..../faq">Questions</a></li>
    <li><a href="http://www..../news">News</a></li>
    <li><a href="http://www..../contact">Contact</a></li>
  </ul> </div>
  <div id="main"> <%= yield %>
  </div>
</div>

</body>
</html>

app/views/others/users.html.erb
<tbody>
<% @users = User.all %>
<tr>
<% @users.each do |user| %>
<td>
    <%= user.email %><br/>
</td>
      </tr>
<% end %>

</tbody>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_url %><br>
    <%= f.text_field :file_url %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchases</h1>

<table>
  <thead>
    <tr>
      <th>File url</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.file_url %></td>
        <td><%= purchase.comments %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File url:</strong>
  <%= @purchase.file_url %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @purchase.comments %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>